export const GET_NEWSLIST = 'GET_NEWSLIST'

export const ROUTERCHANGE = 'ROUTERCHANGE'

export const PULLDOWNBTN = 'PULLDOWNBTN'

export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE'

export const RETURN = 'RETURN'
